---
title: "Test" 

output: bookdown::html_document2
author: T.S.
date: "`r Sys.Date()`"
---

# Summary

Objective of the analysis is the prediction of five different classes of of barbell lifts performed by six test-participants based on data from accelerometers attached to the belt, forearm, arm, and dumbbell. A training data set with   

```{r import, echo=FALSE}

options(tidyverse.quiet = TRUE)

suppressPackageStartupMessages({
  suppressMessages({
    library(tidyverse)
    library(lubridate)
    library(caret)
    library(doParallel)
    library(lime)
  })
})  

theme_set(theme_light())

# Load Data
suppressWarnings({
pml_training <- readr::read_csv("pml-training.csv", 
                                na=c("", "#DIV/0!", "NA"), 
                                progress = F,
                                col_types = cols())

pml_testing  <- readr::read_csv("pml-testing.csv",
                                na=c("", "#DIV/0!", "NA"), 
                                progress = F,
                                col_types = cols())})

# Collect Informations
missingValues <- sapply(pml_training, function(x) sum(is.na(x)))
missingValues <- missingValues[missingValues>0]
userNames <- unique(pml_training$user_name)

# Prepare Data
prepare <- function(x,.train=T) {
  x$cvtd_timestamp <- x$raw_timestamp_part_1 +  x$raw_timestamp_part_2/1000000
  x$raw_timestamp_part_1 <- NULL
  x$raw_timestamp_part_2 <- NULL
  x$X1 <- NULL
  if(.train)
    x$classe <- as.factor(x$classe)
  x$user_name <- factor(x$user_name,userNames)
  x$new_window <- NULL
  x %>% select(-matches(names(missingValues)))
} 

pml_training <- prepare(pml_training)
pml_testing <- prepare(pml_testing,F)
```

```{r split}

# Prepare Center and Scale
prepare <- preProcess(pml_training,
                      method = c("center", "scale"))
                      
# Split Dataset
inTraining <- createDataPartition(pml_training$classe, 
                                  p = .8, 
                                  list = T)

train <- pml_training[inTraining$Resample1,] 
validate <- pml_training[-inTraining$Resample1,]

# Apply Center and Scale
train <- predict(prepare, train)
validate <- predict(prepare, validate)
test <- predict(prepare, pml_testing)

# Crossfold Validation x5
fitControl <- trainControl(method = "repeatedcv",
                           number = 5,
                           repeats = 5,
                           savePredictions=TRUE,
                           classProbs=TRUE)
```

```{r training}

# Prepare Parallel Computing
cl <- makePSOCKcluster(6)
registerDoParallel(cl)

set.seed(825)

# Model training
if(!file.exists("model_rpartFit.rda")) {
  rpartFit <- train(classe ~ ., 
                       data = train, 
                       method = 'rpart',
                       trControl = fitControl,
                       metric = 'Accuracy',
                       tuneLength  = 6)
  save(rpartFit, file="model_rpartFit.rda") 
}

if(!file.exists("model_rfFit.rda")) {
  rfFit <- train(classe ~ ., 
                 data = train, 
                 method = 'rf',
                 trControl = fitControl,
                 metric = 'Accuracy',
                 tuneLength  = 6)
  save(rfFit, file="model_rfFit.rda")
}

if(!file.exists("model_glmnet.rda")) {
  glmFit <- train(classe ~ ., 
                 data = train, 
                 method = "glmnet",
                 trControl = fitControl,
                 metric = 'Accuracy',
                 tuneLength  = 6, 
                 family = "multinomial", 
                 type.multinomial = "grouped")
  save(glmFit, file="model_glmnet.rda")
}
                  
stopCluster(cl)
```

```{r evaluation}

getEvaluationData <- function(model, name, data) {
    tibble(Method = model$method,
           Dataset = name,
           broom::tidy(confusionMatrix( data=predict(model, data), 
                                        reference=data$classe)))
}

load("model_rpartFit.rda")
load("model_rfFit.rda")
load("model_glmnet.rda")

performance <- tibble() %>% 
                bind_rows(getEvaluationData(rpartFit, "Training", train),
                          getEvaluationData(rpartFit, "Validate", validate),
                          getEvaluationData(rfFit, "Training", train),
                          getEvaluationData(rfFit, "Validate", validate),
                          getEvaluationData(glmFit, "Training", train),
                          getEvaluationData(glmFit, "Validate", validate))

ggplot(performance %>% filter(term == "accuracy"),
       aes(x=estimate,
           xmin=conf.low,
           xmax=conf.high,
           y=Method)) +
  geom_errorbar() +
  geom_point() +
  facet_wrap(.~Dataset) +
  xlab("Accuracy") +
  scale_x_continuous(labels=scales::label_percent(accuracy = 1),
                     trans="log10") +
  labs(title="Model Performance",
       subtitle = "Prediction Accuracy based on train and validation data")
```

```{r model}

tibble(N = 1:nrow(test), 
       Classe=predict(rfFit, test))

```


